package search

// ---------------------------------------------------------------------
// Type Definitions
// ---------------------------------------------------------------------
type Link struct {
	URL     string
	Heading string
}

// Parse extracts links from the HTML generated by a Google search.
func Parse(html string) ([]Link, error) {
	return nil, nil
}
